#!/usr/bin/python
#Texpert Text Editor 

import os
os.system('clear')
import time
import datetime
import platform

import Tkinter
from Tkinter import *
from ScrolledText import *
import tkFileDialog
import tkMessageBox

#main window
root = Tkinter.Tk(className = "texpert")
textPad = ScrolledText(root, width=90, height=26, undo=True)
root.resizable(width=False, height=False)


#define menu functions
#file menu
def new_com(): 
    root.title("Untitled ") 
    file = None
    textPad.delete(1.0,END) 

def open_com():
    file = tkFileDialog.askopenfile(parent=root, mode='rb', title='Select File')
    if file != None:
  	contents = file.read()
	textPad.insert('1.0', contents)
	file.close()

def save_com():
    file = tkFileDialog.asksaveasfile(mode='w')
    if file != None:
	data = textPad.get('1.0', END+'-1c')
	file.write(data)
 	file.close()

def exit_com():
    if tkMessageBox.askokcancel("Exit", "Do you really want to exit?"):
	root.destroy()

#edit menu
def undo_com():
    textPad.edit_undo()

def redo_com():
    textPad.edit_redo()

def cut_com(): 
    textPad.event_generate("<<Cut>>")

def copy_com(): 
    textPad.event_generate("<<Copy>>") 

def paste_com(): 
    textPad.event_generate("<<Paste>>")  

def select_all():
    textPad.tag_add(SEL, "1.0", END)
    textPad.mark_set(INSERT, "1.0")
    textPad.see(INSERT)
    return 'break'

textPad.bind("<Control-Key-a>", select_all)
textPad.bind("<Control-Key-A>", select_all) #for caps

#tools menu
def date_com():
    full_date = time.localtime()
    day = str(full_date.tm_mday)
    month = str(full_date.tm_mon)
    year = str(full_date.tm_year)
    date = ""+month+'/'+day+'/'+year
    textPad.insert(INSERT, date, "a")

#help menu
def about_com():
    label = tkMessageBox.showinfo("About", "Texpert \nText Editor \nVersion 2.0 ")

def info_com():
    label = tkMessageBox.showinfo("Info", "Text Editor \nMade in Python \nwith Tkinter ")


#add menu (labels)
menu = Menu(root)
root.config(menu=menu)

filemenu = Menu(menu)
menu.add_cascade(label="File ", menu=filemenu)
filemenu.add_command(label="New", command=new_com) 
filemenu.add_command(label="Open", command=open_com)
filemenu.add_separator()
filemenu.add_command(label="Save", command=save_com)
filemenu.add_command(label="Save As", command=save_com)
filemenu.add_separator()
filemenu.add_command(label="Exit", command=exit_com)

editmenu = Menu(menu)
menu.add_cascade(label="Edit ", menu=editmenu)
editmenu.add_command(label="Undo", command=undo_com)
editmenu.add_command(label="Redo", command=redo_com)
editmenu.add_separator()
editmenu.add_command(label="Cut", command=cut_com)
editmenu.add_command(label="Copy", command=copy_com)  
editmenu.add_command(label="Paste", command=paste_com) 
editmenu.add_separator()
editmenu.add_command(label="Select All        Ctrl+a", command=select_all) 

toolmenu = Menu(menu)
menu.add_cascade(label="Tools ", menu=toolmenu)
toolmenu.add_command(label="Insert Date", command=date_com)

helpmenu = Menu(menu)
menu.add_cascade(label="Help ", menu=helpmenu)
helpmenu.add_command(label="About", command=about_com)
helpmenu.add_command(label="Info", command=info_com)



textPad.pack()

#image/quote
text1 = Text(root, height=12, width=23, background='black')
photo=PhotoImage(file='/home/ravid/Pictures/icons/redhat.png') #change accordingly
text1.insert(END,'\n')
text1.image_create(END, image=photo)
text1.pack(side=LEFT)

text2 = Text(root, height=12, width=66, background='black')
scroll = Scrollbar(root, command=text2.yview)
text2.configure(yscrollcommand=scroll.set)
text2.tag_configure('big', foreground='white', font=('Verdana', 18, 'bold'))
text2.tag_configure('color', foreground='green', font=('Tempus Sans ITC', 12, 'bold'))
text2.tag_configure('normal', foreground='red', font=('Arial', 10))
text2.insert(END,'\n Linux\n', 'big') 
quote = """
 where there's a shell, there's a way_
"""
text2.insert(END, quote, 'color')
text2.insert(END, '\n\n  redhat\n', 'normal')
text2.pack(side=LEFT)
scroll.pack(side=RIGHT, fill=Y)

root.mainloop()
 
