#!/usr/bin/python
#Texpert Text Editor 

import os
os.system('clear')
import time
import datetime
import platform

import Tkinter
from Tkinter import *
from ScrolledText import *
import tkFileDialog
import tkMessageBox

#main window
root = Tkinter.Tk(className = "Texpert")
textPad = ScrolledText(root, width=98, height=26, bg="white", undo=True)
root.resizable(width=False, height=False)


#define menu functions
# file menu
def new_com(): 
    root.title("Untitled ") 
    file = None
    textPad.delete(1.0,END) 

def open_com():
    file = tkFileDialog.askopenfile(parent=root, mode='rb', title='Select File')
    if file != None:
  	contents = file.read()
	textPad.insert('1.0', contents)
	file.close()

def save_com():
    file = tkFileDialog.asksaveasfile(mode='w')
    if file != None:
	data = textPad.get('1.0', END+'-1c')
	file.write(data)
 	file.close()

def exit_com():
    if tkMessageBox.askokcancel("Exit", "Do you really want to exit?"):
	root.destroy()

# edit menu
def undo_com():
    textPad.edit_undo()

def redo_com():
    textPad.edit_redo()

def cut_com(): 
    textPad.event_generate("<<Cut>>")

def copy_com(): 
    textPad.event_generate("<<Copy>>") 

def paste_com(): 
    textPad.event_generate("<<Paste>>")  

def select_all():
    textPad.tag_add(SEL, "1.0", END)
    textPad.mark_set(INSERT, "1.0")
    textPad.see(INSERT)
    return 'break'

textPad.bind("<Control-Key-a>", select_all)
textPad.bind("<Control-Key-A>", select_all)

# tools menu
def time_com():
    ctime = time.strftime('%I:%M:%p')
    textPad.insert(INSERT, ctime, "a")

def date_com():
    full_date = time.localtime()
    day = str(full_date.tm_mday)
    month = str(full_date.tm_mon)
    year = str(full_date.tm_year)
    date = ""+month+'/'+day+'/'+year
    textPad.insert(INSERT, date, "a")

# help menu
def about_com():
    label = tkMessageBox.showinfo("About", "Texpert \n\nA small text editor \ndesigned for linux. \n\nVersion 2.4 \n")

def info_com():
    label = tkMessageBox.showinfo("Info", "Text Editor \n\nMade in Python \nwith Tkinter ")

def trouble_com():
    label = tkMessageBox.showinfo("Troubleshooting", "This program was designed for linux and may not work on other operating systems. \n\nTexpert text editor is a work in progress and is not yet complete. \n\nA 'right click' menu has not yet been incorporated (will fix). \n\nThe 'Save' and 'Save As' options both work as 'save as'. This will be corrected. \n\n('>\n//)\n|\\ ")

#add menu (labels)
menu = Menu(root)
root.config(menu=menu)

filemenu = Menu(menu)
menu.add_cascade(label="File ", menu=filemenu)
filemenu.add_command(label="New", command=new_com) 
filemenu.add_command(label="Open", command=open_com)
filemenu.add_separator()
filemenu.add_command(label="Save", command=save_com)
filemenu.add_command(label="Save As", command=save_com)
filemenu.add_separator()
filemenu.add_command(label="Exit", command=exit_com)

editmenu = Menu(menu)
menu.add_cascade(label="Edit ", menu=editmenu)
editmenu.add_command(label="Undo", command=undo_com)
editmenu.add_command(label="Redo", command=redo_com)
editmenu.add_separator()
editmenu.add_command(label="Cut", command=cut_com)
editmenu.add_command(label="Copy", command=copy_com)  
editmenu.add_command(label="Paste", command=paste_com) 
editmenu.add_separator()
editmenu.add_command(label="Select All        Ctrl+a", command=select_all) 

toolmenu = Menu(menu)
menu.add_cascade(label="Tools ", menu=toolmenu)
toolmenu.add_command(label="Insert Time", command=time_com)
toolmenu.add_command(label="Insert Date", command=date_com)

helpmenu = Menu(menu)
menu.add_cascade(label="Help ", menu=helpmenu)
helpmenu.add_command(label="About", command=about_com)
helpmenu.add_command(label="Info", command=info_com)
helpmenu.add_command(label="Troubleshooting", command=trouble_com)


#toolbar]
toolbar = Frame(root)
b = Button(toolbar, text="Open", width=4, command=open_com)
b.pack(side=LEFT, padx=2, pady=2)
b = Button(toolbar, text="Save", width=4, command=save_com)
b.pack(side=RIGHT, padx=2, pady=2)

toolbar.pack(side=TOP, fill=X)

#statusBar mess]
status = Label(text="Dont forget to save your work. And brush your teeth! ", bd=1, relief=SUNKEN, anchor=W, border=0)
status.pack(side=BOTTOM, fill=Y)
textPad.pack()

#imageBox (lower left)
imageBox = Text(root, height=12, width=24, background='black')
photo=PhotoImage(file='/home/ravid/Pictures/icons/redhat.png') #change accordingly
imageBox.insert(END,'\n')
imageBox.image_create(END, image=photo)
imageBox.pack(side=LEFT)

#textBox (lower right)
textBox = Text(root, height=12, width=73, background='black')
scroll = Scrollbar(root, command=textBox.yview)
textBox.configure(yscrollcommand=scroll.set)
textBox.tag_configure('big', foreground='white', font=('Verdana', 18, 'bold'))
textBox.tag_configure('color', foreground='green', font=('Tempus Sans ITC', 12, 'bold'))
textBox.tag_configure('normal', foreground='red', font=('Arial', 10))
textBox.insert(END, '\n Linux\n', 'big') 
textBox.insert(END, '\n where there\'s a shell, there\'s a way_ \n', 'color')
textBox.insert(END, '\n\n  redhat\n', 'normal')
textBox.pack(side=LEFT)
scroll.pack(side=RIGHT, fill=Y)

root.mainloop()
 
